### ISSUE TITLE
How to properly credit this repository?

### ISSUE THREAD

**Issue by wzx16** [jimmyyhwu/spatial-action-maps#2]
Hi Jimmy,

I found this repo comes with MIT license, so I was wondering what is the preferred way to credit this repo? I am publishing a github project page, which contains a implementation of a project based on spatial action map code(awesome work Jimmy!). Thanks!

Best,

**Comment by jimmyyhwu** [comment]
Thanks for the interest in our work! Feel free to cite the paper, fork the repo, or link to the [project page](https://spatial-action-maps.cs.princeton.edu), whichever works best for you.
